name: Multi-Job Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run job-1 script
        run: |
          echo "Running job-1"
          # exit 1
          
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run job-2 script
        run: echo "Running job-2"

  job-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run job-3 script
        run: echo "Running job-3"

  check-status:
    runs-on: ubuntu-latest
    needs: [job-1, job-2, job-3]
    if: always() && (needs.job-1.result == 'success' || needs.job-2.result == 'success' || needs.job-3.result == 'success')
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.APPROVAL }}
          number: 6
