name: Multi-Job Workflow

on:
  # workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-status:
    runs-on: arc-runner-set
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.APPROVAL }}
          number: ${{ github.event.pull_request.number }}
